In [ ]:
!pip install catboost -q

In [ ]:
import kagglehub
import numpy as np
import pandas as pd
import warnings
from tqdm.auto import tqdm
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score, accuracy_score, precision_score, recall_score
from sklearn.utils import resample
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

warnings.filterwarnings('ignore')

In [ ]:
def inject_missing_data(X, ratio, random_seed=42):
    if ratio == 0:
        return X.copy()
    np.random.seed(random_seed)
    X_miss = X.copy()
    mask = np.random.rand(*X_miss.shape) < ratio
    X_miss = X_miss.mask(mask)
    return X_miss

def evaluate_with_bootstrap(model, X_test, y_test, n_iterations=1000):
    metrics = {'roc_auc': [], 'f1': [], 'accuracy': [], 'precision': [], 'recall': []}
    is_multiclass = len(np.unique(y_test)) > 2
    avg_method = 'macro' if is_multiclass else 'binary'

    for _ in range(n_iterations):
        X_boot, y_boot = resample(X_test, y_test)
        if len(np.unique(y_boot)) < 2: continue

        y_pred = model.predict(X_boot)
        y_prob = model.predict_proba(X_boot)

        try:
            if is_multiclass: metrics['roc_auc'].append(roc_auc_score(y_boot, y_prob, multi_class='ovr'))
            else: metrics['roc_auc'].append(roc_auc_score(y_boot, y_prob[:, 1]))

            metrics['f1'].append(f1_score(y_boot, y_pred, average=avg_method, zero_division=0))
            metrics['accuracy'].append(accuracy_score(y_boot, y_pred))
            metrics['precision'].append(precision_score(y_boot, y_pred, average=avg_method, zero_division=0))
            metrics['recall'].append(recall_score(y_boot, y_pred, average=avg_method, zero_division=0))
        except: continue

    results = {}
    for k, v in metrics.items():
        if len(v) == 0: results[k] = "N/A"
        else: results[k] = f"{np.mean(v):.4f}±{1.96 * np.std(v):.4f}"
    return results

def load_and_prep_data(dataset_name):
    dataset_ids = {'Bank': 1461, 'Blood': 1464, 'California': 44090, 'Car': 40975,
                   'Credit-G': 31, 'Diabetes': 37, 'Heart': 53, 'Income': 1590, 'Jungle': 41027}
    if dataset_name == 'Diabetes':
        path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database") + "/diabetes.csv"
        df = pd.read_csv(path); X, y = df.drop(columns=['Outcome']), df['Outcome']
    elif dataset_name == 'Heart':
        path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction") + "/heart.csv"
        df = pd.read_csv(path); X, y = df.drop(columns=['HeartDisease']), df['HeartDisease']
    else:
        data = fetch_openml(data_id=dataset_ids[dataset_name], as_frame=True, parser='auto')
        X, y = data.data, data.target
    le = LabelEncoder()
    y = le.fit_transform(y.astype(str))
    return X, y

def run_logistic_regression(X_train, X_test, y_train, y_test):
    cat_cols = X_train.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
    num_cols = X_train.select_dtypes(exclude=['object', 'category', 'string']).columns.tolist()
    num_pipe = Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())])
    cat_pipe = Pipeline([('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
                         ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
    preprocessor = ColumnTransformer([('num', num_pipe, num_cols), ('cat', cat_pipe, cat_cols)])
    pipe = Pipeline([('prep', preprocessor), ('clf', LogisticRegression(max_iter=1000, random_state=42))])
    pipe.fit(X_train, y_train)
    return evaluate_with_bootstrap(pipe, X_test, y_test)

def run_catboost(X_train, X_test, y_train, y_test):
    cat_features = X_train.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
    X_tr, X_te = X_train.copy(), X_test.copy()
    for col in cat_features:
        X_tr[col] = X_tr[col].astype(str).replace('nan', 'missing')
        X_te[col] = X_te[col].astype(str).replace('nan', 'missing')
    model = CatBoostClassifier(iterations=1000, learning_rate=0.1, depth=6, cat_features=cat_features,
                               verbose=0, random_seed=42, nan_mode='Min', task_type='GPU')
    model.fit(X_tr, y_train)
    return evaluate_with_bootstrap(model, X_te, y_test)

def run_lightgbm(X_train, X_test, y_train, y_test):
    X_tr, X_te = X_train.copy(), X_test.copy()
    cat_cols = X_tr.select_dtypes(include=['object', 'string', 'category']).columns
    for col in cat_cols:
        X_tr[col] = X_tr[col].astype('category')
        X_te[col] = X_te[col].astype('category')
    model = LGBMClassifier(n_estimators=1000, random_state=42, verbose=-1, device='gpu')
    model.fit(X_tr, y_train)
    return evaluate_with_bootstrap(model, X_te, y_test)

In [ ]:
datasets = ["Bank", "Blood", "California", "Car", "Credit-G", "Diabetes", "Heart", "Income", "Jungle"]
missing_ratios = [0.0, 0.2, 0.5, 0.9]

preloaded_data = {}
for ds_name in tqdm(datasets, desc="Подготовка данных"):
    preloaded_data[ds_name] = load_and_prep_data(ds_name)

Подготовка данных:   0%|          | 0/9 [00:00<?, ?it/s]

Using Colab cache for faster access to the 'pima-indians-diabetes-database' dataset.
Using Colab cache for faster access to the 'heart-failure-prediction' dataset.

In [ ]:
# Logistic Regression
lr_results = []
for ds_name in tqdm(datasets, desc="Logistic Regression"):
    X_orig, y = preloaded_data[ds_name]
    X_train_val, X_test_clean, y_train_val, y_test = train_test_split(X_orig, y, test_size=0.2, random_state=42, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val)

    for ratio in tqdm(missing_ratios):
        X_test_noisy = inject_missing_data(X_test_clean, ratio, random_seed=42)
        res = run_logistic_regression(X_train, X_test_noisy, y_train, y_test)
        lr_results.append({'Dataset': ds_name, 'Missing_Ratio': f"{int(ratio*100)}%", 'Model': 'LogReg', **res})

lr_df = pd.DataFrame(lr_results)

display(lr_df)

Logistic Regression:   0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,LogReg,0.9057±0.0092,0.4496±0.0306,0.9014±0.0060,0.6480±0.0402,0.3444±0.0290
1,Bank,20%,LogReg,0.8583±0.0122,0.4404±0.0296,0.8972±0.0060,0.6060±0.0395,0.3461±0.0282
2,Bank,50%,LogReg,0.7779±0.0159,0.3698±0.0304,0.8887±0.0063,0.5474±0.0436,0.2794±0.0268
3,Bank,90%,LogReg,0.6090±0.0182,0.1284±0.0257,0.8802±0.0066,0.4303±0.0716,0.0755±0.0161
4,Blood,0%,LogReg,0.7869±0.0889,0.1809±0.1546,0.7685±0.0658,0.5654±0.4052,0.1101±0.1019
5,Blood,20%,LogReg,0.7913±0.0753,0.2295±0.1668,0.7862±0.0656,0.8345±0.3363,0.1359±0.1109
6,Blood,50%,LogReg,0.7499±0.0794,0.0979±0.1300,0.7667±0.0668,0.6340±0.6748,0.0542±0.0754
7,Blood,90%,LogReg,0.5854±0.0914,0.0000±0.0000,0.7536±0.0683,0.0000±0.0000,0.0000±0.0000
8,California,0%,LogReg,0.9138±0.0083,0.8374±0.0119,0.8365±0.0110,0.8320±0.0163,0.8428±0.0155
9,California,20%,LogReg,0.7876±0.0136,0.7413±0.0146,0.7393±0.0133,0.7351±0.0191,0.7477±0.0186
10,California,50%,LogReg,0.6761±0.0163,0.6571±0.0159,0.6424±0.0143,0.6307±0.0198,0.6859±0.0197
11,California,90%,LogReg,0.5407±0.0168,0.6333±0.0150,0.5225±0.0156,0.5138±0.0168,0.8254±0.0166
12,Car,0%,LogReg,0.9876±0.0059,0.7910±0.0801,0.9028±0.0309,0.8418±0.0766,0.7597±0.0914
13,Car,20%,LogReg,0.9379±0.0192,0.5196±0.0912,0.7947±0.0426,0.5639±0.1156,0.5002±0.0865
14,Car,50%,LogReg,0.8568±0.0338,0.2853±0.0300,0.7138±0.0484,0.2985±0.0405,0.2944±0.0241
15,Car,90%,LogReg,0.6087±0.0579,0.2116±0.0157,0.6973±0.0494,0.2567±0.1573,0.2513±0.0071
16,Credit-G,0%,LogReg,0.7603±0.0678,0.8054±0.0501,0.7205±0.0627,0.7854±0.0686,0.8276±0.0612
17,Credit-G,20%,LogReg,0.7102±0.0781,0.8188±0.0497,0.7402±0.0631,0.7963±0.0642,0.8435±0.0613
18,Credit-G,50%,LogReg,0.7048±0.0814,0.8339±0.0450,0.7387±0.0621,0.7485±0.0639,0.9422±0.0397
19,Credit-G,90%,LogReg,0.5609±0.0870,0.8209±0.0429,0.6984±0.0613,0.7002±0.0615,0.9931±0.0136
20,Diabetes,0%,LogReg,0.8206±0.0705,0.5696±0.1211,0.7278±0.0732,0.6351±0.1492,0.5205±0.1352
21,Diabetes,20%,LogReg,0.7987±0.0703,0.5532±0.1258,0.7450±0.0712,0.7130±0.1508,0.4556±0.1335
22,Diabetes,50%,LogReg,0.7622±0.0750,0.3706±0.1375,0.6800±0.0731,0.5936±0.1947,0.2726±0.1214
23,Diabetes,90%,LogReg,0.6509±0.0793,0.0320±0.0623,0.6304±0.0752,0.1928±0.3906,0.0177±0.0350
24,Heart,0%,LogReg,0.9204±0.0437,0.8935±0.0445,0.8790±0.0469,0.8688±0.0644,0.9207±0.0527
25,Heart,20%,LogReg,0.9270±0.0419,0.8707±0.0517,0.8586±0.0527,0.8799±0.0644,0.8628±0.0695
26,Heart,50%,LogReg,0.8871±0.0513,0.8197±0.0599,0.8097±0.0584,0.8610±0.0720,0.7836±0.0793
27,Heart,90%,LogReg,0.6675±0.0800,0.3772±0.1021,0.5544±0.0700,0.8363±0.1385,0.2450±0.0805
28,Income,0%,LogReg,0.9053±0.0062,0.6598±0.0158,0.8533±0.0069,0.7404±0.0191,0.5951±0.0193
29,Income,20%,LogReg,0.8684±0.0074,0.5321±0.0194,0.8270±0.0074,0.7521±0.0237,0.4118±0.0195
30,Income,50%,LogReg,0.7934±0.0097,0.3159±0.0216,0.7943±0.0082,0.7707±0.0328,0.1987±0.0160
31,Income,90%,LogReg,0.6143±0.0127,0.0310±0.0097,0.7636±0.0086,0.7725±0.1254,0.0158±0.0050
32,Jungle,0%,LogReg,0.8090±0.0071,0.5035±0.0106,0.6758±0.0095,0.5465±0.0226,0.5091±0.0083
33,Jungle,20%,LogReg,0.7764±0.0081,0.4749±0.0100,0.6517±0.0097,0.5334±0.0290,0.4850±0.0080
34,Jungle,50%,LogReg,0.7156±0.0092,0.4238±0.0085,0.6073±0.0101,0.5104±0.0498,0.4397±0.0073
35,Jungle,90%,LogReg,0.5723±0.0093,0.3043±0.0068,0.5352±0.0101,0.3610±0.0110,0.3590±0.0045

In [ ]:
# CatBoost
cat_results = []
for ds_name in tqdm(datasets, desc="CatBoost"):
    X_orig, y = preloaded_data[ds_name]
    X_train_val, X_test_clean, y_train_val, y_test = train_test_split(X_orig, y, test_size=0.2, random_state=42, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val)

    for ratio in tqdm(missing_ratios):
        X_test_noisy = inject_missing_data(X_test_clean, ratio, random_seed=42)
        res = run_catboost(X_train, X_test_noisy, y_train, y_test)
        cat_results.append({'Dataset': ds_name, 'Missing_Ratio': f"{int(ratio*100)}%", 'Model': 'CatBoost', **res})

cat_df = pd.DataFrame(cat_results)

display(cat_df)

CatBoost:   0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,CatBoost,0.9307±0.0066,0.5422±0.0273,0.9075±0.0059,0.6431±0.0335,0.4688±0.0298
1,Bank,20%,CatBoost,0.7625±0.0155,0.3701±0.0248,0.8468±0.0073,0.3565±0.0267,0.3850±0.0287
2,Bank,50%,CatBoost,0.6474±0.0189,0.2522±0.0270,0.8520±0.0073,0.3082±0.0341,0.2136±0.0250
3,Bank,90%,CatBoost,0.5264±0.0179,0.0150±0.0100,0.8826±0.0064,0.4024±0.2211,0.0076±0.0051
4,Blood,0%,CatBoost,0.7455±0.0972,0.4545±0.1564,0.7816±0.0680,0.5601±0.1995,0.3882±0.1598
5,Blood,20%,CatBoost,0.6168±0.1066,0.1604±0.1337,0.7272±0.0700,0.3093±0.2507,0.1108±0.0990
6,Blood,50%,CatBoost,0.5631±0.1063,0.0969±0.1192,0.7535±0.0680,0.3936±0.4648,0.0565±0.0724
7,Blood,90%,CatBoost,0.5239±0.0963,0.0000±0.0000,0.7602±0.0681,0.0000±0.0000,0.0000±0.0000
8,California,0%,CatBoost,0.9618±0.0051,0.8933±0.0098,0.8927±0.0093,0.8870±0.0135,0.8998±0.0131
9,California,20%,CatBoost,0.7970±0.0134,0.7764±0.0127,0.7472±0.0128,0.6956±0.0172,0.8786±0.0138
10,California,50%,CatBoost,0.6202±0.0173,0.6959±0.0138,0.5986±0.0152,0.5599±0.0166,0.9194±0.0115
11,California,90%,CatBoost,0.5108±0.0164,0.6679±0.0132,0.5087±0.0149,0.5043±0.0149,0.9889±0.0045
12,Car,0%,CatBoost,0.9985±0.0018,0.9476±0.0469,0.9801±0.0144,0.9661±0.0405,0.9352±0.0619
13,Car,20%,CatBoost,0.9303±0.0223,0.6686±0.0903,0.8346±0.0368,0.6539±0.0957,0.7005±0.0995
14,Car,50%,CatBoost,0.8090±0.0470,0.4417±0.0835,0.6583±0.0486,0.4662±0.1177,0.4765±0.0850
15,Car,90%,CatBoost,0.5575±0.0566,0.1900±0.0531,0.3260±0.0531,0.3287±0.0840,0.2903±0.0396
16,Credit-G,0%,CatBoost,0.7605±0.0732,0.8410±0.0456,0.7567±0.0618,0.7745±0.0659,0.9212±0.0456
17,Credit-G,20%,CatBoost,0.6288±0.0860,0.7928±0.0485,0.6885±0.0627,0.7390±0.0644,0.8561±0.0590
18,Credit-G,50%,CatBoost,0.5888±0.0840,0.7862±0.0495,0.6679±0.0644,0.7131±0.0657,0.8772±0.0562
19,Credit-G,90%,CatBoost,0.5130±0.0951,0.8115±0.0460,0.6931±0.0640,0.7093±0.0644,0.9494±0.0358
20,Diabetes,0%,CatBoost,0.7994±0.0751,0.5937±0.1155,0.7273±0.0727,0.6178±0.1383,0.5757±0.1343
21,Diabetes,20%,CatBoost,0.7652±0.0749,0.4779±0.1283,0.7076±0.0731,0.6360±0.1612,0.3865±0.1296
22,Diabetes,50%,CatBoost,0.6772±0.0885,0.2783±0.1361,0.6745±0.0737,0.6216±0.2442,0.1818±0.1023
23,Diabetes,90%,CatBoost,0.5289±0.0894,0.0337±0.0655,0.6496±0.0737,0.4188±0.7645,0.0177±0.0350
24,Heart,0%,CatBoost,0.9337±0.0385,0.8832±0.0477,0.8741±0.0486,0.9060±0.0605,0.8625±0.0671
25,Heart,20%,CatBoost,0.8681±0.0565,0.8298±0.0572,0.8046±0.0611,0.8008±0.0778,0.8624±0.0675
26,Heart,50%,CatBoost,0.7903±0.0679,0.7870±0.0616,0.7544±0.0636,0.7569±0.0800,0.8212±0.0751
27,Heart,90%,CatBoost,0.5408±0.0819,0.6810±0.0660,0.5485±0.0730,0.5598±0.0770,0.8719±0.0665
28,Income,0%,CatBoost,0.9302±0.0053,0.7198±0.0145,0.8784±0.0064,0.8014±0.0178,0.6534±0.0187
29,Income,20%,CatBoost,0.8432±0.0090,0.4553±0.0217,0.8236±0.0077,0.8689±0.0233,0.3085±0.0189
30,Income,50%,CatBoost,0.7366±0.0115,0.1543±0.0180,0.7797±0.0082,0.9378±0.0325,0.0841±0.0106
31,Income,90%,CatBoost,0.5789±0.0127,0.0034±0.0033,0.7614±0.0087,0.9790±0.2810,0.0017±0.0017
32,Jungle,0%,CatBoost,0.9717±0.0021,0.8085±0.0105,0.8583±0.0072,0.8137±0.0117,0.8038±0.0112
33,Jungle,20%,CatBoost,0.8039±0.0088,0.6037±0.0129,0.6800±0.0100,0.6173±0.0139,0.6034±0.0126
34,Jungle,50%,CatBoost,0.6428±0.0101,0.4252±0.0119,0.5271±0.0100,0.4577±0.0159,0.4312±0.0100
35,Jungle,90%,CatBoost,0.5089±0.0092,0.3039±0.0073,0.4870±0.0105,0.3213±0.0366,0.3346±0.0063

In [ ]:
# LightGBM
lgb_results = []
for ds_name in tqdm(datasets, desc="LightGBM"):
    X_orig, y = preloaded_data[ds_name]
    X_train_val, X_test_clean, y_train_val, y_test = train_test_split(X_orig, y, test_size=0.2, random_state=42, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val)

    for ratio in tqdm(missing_ratios):
        X_test_noisy = inject_missing_data(X_test_clean, ratio, random_seed=42)
        res = run_lightgbm(X_train, X_test_noisy, y_train, y_test)
        lgb_results.append({'Dataset': ds_name, 'Missing_Ratio': f"{int(ratio*100)}%", 'Model': 'LightGBM', **res})

lgb_df = pd.DataFrame(lgb_results)

display(lgb_df)

LightGBM:   0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,LightGBM,0.9238±0.0070,0.5423±0.0272,0.9069±0.0058,0.6372±0.0332,0.4723±0.0303
1,Bank,20%,LightGBM,0.7904±0.0156,0.4098±0.0281,0.8802±0.0065,0.4834±0.0343,0.3559±0.0288
2,Bank,50%,LightGBM,0.6428±0.0195,0.2579±0.0287,0.8706±0.0068,0.3917±0.0415,0.1924±0.0240
3,Bank,90%,LightGBM,0.5073±0.0194,0.0347±0.0156,0.8821±0.0065,0.4064±0.1449,0.0181±0.0083
4,Blood,0%,LightGBM,0.7017±0.0964,0.4426±0.1441,0.7543±0.0697,0.4817±0.1746,0.4155±0.1554
5,Blood,20%,LightGBM,0.6585±0.1076,0.4008±0.1493,0.7260±0.0713,0.4220±0.1715,0.3878±0.1634
6,Blood,50%,LightGBM,0.5972±0.1160,0.3612±0.1464,0.6997±0.0749,0.3698±0.1619,0.3593±0.1644
7,Blood,90%,LightGBM,0.5109±0.0876,0.0911±0.1158,0.7400±0.0693,0.2868±0.3595,0.0556±0.0738
8,California,0%,LightGBM,0.9656±0.0050,0.9033±0.0094,0.9029±0.0089,0.8983±0.0132,0.9085±0.0125
9,California,20%,LightGBM,0.7547±0.0149,0.7351±0.0150,0.7426±0.0128,0.7566±0.0187,0.7150±0.0191
10,California,50%,LightGBM,0.5988±0.0172,0.5401±0.0194,0.5897±0.0148,0.6138±0.0239,0.4824±0.0217
11,California,90%,LightGBM,0.5244±0.0166,0.1855±0.0200,0.5096±0.0145,0.5453±0.0466,0.1118±0.0133
12,Car,0%,LightGBM,0.9990±0.0019,0.9560±0.0501,0.9886±0.0110,0.9738±0.0387,0.9425±0.0620
13,Car,20%,LightGBM,0.9434±0.0222,0.6695±0.1012,0.8499±0.0370,0.7475±0.1082,0.6508±0.1008
14,Car,50%,LightGBM,0.8546±0.0344,0.4042±0.0827,0.7607±0.0466,0.5079±0.1737,0.3860±0.0623
15,Car,90%,LightGBM,0.6014±0.0558,0.2382±0.0270,0.6851±0.0493,0.2637±0.0573,0.2602±0.0181
16,Credit-G,0%,LightGBM,0.6853±0.0804,0.7931±0.0518,0.7040±0.0636,0.7760±0.0708,0.8122±0.0626
17,Credit-G,20%,LightGBM,0.6412±0.0884,0.7900±0.0507,0.6938±0.0633,0.7566±0.0648,0.8276±0.0643
18,Credit-G,50%,LightGBM,0.6001±0.0901,0.7764±0.0527,0.6738±0.0655,0.7432±0.0676,0.8140±0.0645
19,Credit-G,90%,LightGBM,0.5561±0.0824,0.8105±0.0461,0.6885±0.0641,0.7035±0.0635,0.9570±0.0349
20,Diabetes,0%,LightGBM,0.8040±0.0726,0.6312±0.1137,0.7528±0.0704,0.6569±0.1343,0.6117±0.1365
21,Diabetes,20%,LightGBM,0.7520±0.0770,0.5055±0.1280,0.7265±0.0703,0.6865±0.1630,0.4036±0.1292
22,Diabetes,50%,LightGBM,0.6454±0.0911,0.2936±0.1356,0.6679±0.0734,0.5747±0.2283,0.1997±0.1062
23,Diabetes,90%,LightGBM,0.5768±0.0883,0.0337±0.0655,0.6497±0.0739,0.4283±0.7867,0.0177±0.0350
24,Heart,0%,LightGBM,0.9255±0.0390,0.8787±0.0477,0.8687±0.0488,0.8973±0.0591,0.8619±0.0683
25,Heart,20%,LightGBM,0.8763±0.0547,0.8759±0.0471,0.8542±0.0510,0.8270±0.0700,0.9320±0.0479
26,Heart,50%,LightGBM,0.8287±0.0612,0.8040±0.0556,0.7494±0.0628,0.7089±0.0777,0.9305±0.0501
27,Heart,90%,LightGBM,0.5788±0.0815,0.7094±0.0601,0.5604±0.0714,0.5600±0.0725,0.9701±0.0329
28,Income,0%,LightGBM,0.9214±0.0058,0.6991±0.0153,0.8667±0.0069,0.7592±0.0190,0.6478±0.0187
29,Income,20%,LightGBM,0.8466±0.0089,0.5048±0.0202,0.8313±0.0076,0.8461±0.0225,0.3597±0.0189
30,Income,50%,LightGBM,0.7525±0.0109,0.2016±0.0204,0.7859±0.0083,0.9271±0.0301,0.1131±0.0127
31,Income,90%,LightGBM,0.6011±0.0120,0.0110±0.0059,0.7623±0.0086,1.0000±0.0000,0.0055±0.0030
32,Jungle,0%,LightGBM,0.9751±0.0020,0.7982±0.0109,0.8565±0.0072,0.8034±0.0120,0.7935±0.0116
33,Jungle,20%,LightGBM,0.8030±0.0087,0.5999±0.0127,0.6785±0.0099,0.6105±0.0136,0.6008±0.0124
34,Jungle,50%,LightGBM,0.6477±0.0097,0.4270±0.0118,0.5259±0.0100,0.4543±0.0151,0.4319±0.0101
35,Jungle,90%,LightGBM,0.5173±0.0092,0.3037±0.0074,0.4847±0.0106,0.3250±0.0331,0.3335±0.0063

In [ ]:
display(lr_df.head())
display(cat_df.head())
display(lgb_df.head())

lr_df.to_csv("results_logistic_regression.csv", index=False)
cat_df.to_csv("results_catboost.csv", index=False)
lgb_df.to_csv("results_lightgbm.csv", index=False)

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,LogReg,0.9057±0.0092,0.4496±0.0306,0.9014±0.0060,0.6480±0.0402,0.3444±0.0290
1,Bank,20%,LogReg,0.8583±0.0122,0.4404±0.0296,0.8972±0.0060,0.6060±0.0395,0.3461±0.0282
2,Bank,50%,LogReg,0.7779±0.0159,0.3698±0.0304,0.8887±0.0063,0.5474±0.0436,0.2794±0.0268
3,Bank,90%,LogReg,0.6090±0.0182,0.1284±0.0257,0.8802±0.0066,0.4303±0.0716,0.0755±0.0161
4,Blood,0%,LogReg,0.7869±0.0889,0.1809±0.1546,0.7685±0.0658,0.5654±0.4052,0.1101±0.1019

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,CatBoost,0.9307±0.0066,0.5422±0.0273,0.9075±0.0059,0.6431±0.0335,0.4688±0.0298
1,Bank,20%,CatBoost,0.7625±0.0155,0.3701±0.0248,0.8468±0.0073,0.3565±0.0267,0.3850±0.0287
2,Bank,50%,CatBoost,0.6474±0.0189,0.2522±0.0270,0.8520±0.0073,0.3082±0.0341,0.2136±0.0250
3,Bank,90%,CatBoost,0.5264±0.0179,0.0150±0.0100,0.8826±0.0064,0.4024±0.2211,0.0076±0.0051
4,Blood,0%,CatBoost,0.7455±0.0972,0.4545±0.1564,0.7816±0.0680,0.5601±0.1995,0.3882±0.1598

,Dataset,Missing_Ratio,Model,roc_auc,f1,accuracy,precision,recall
0,Bank,0%,LightGBM,0.9238±0.0070,0.5423±0.0272,0.9069±0.0058,0.6372±0.0332,0.4723±0.0303
1,Bank,20%,LightGBM,0.7904±0.0156,0.4098±0.0281,0.8802±0.0065,0.4834±0.0343,0.3559±0.0288
2,Bank,50%,LightGBM,0.6428±0.0195,0.2579±0.0287,0.8706±0.0068,0.3917±0.0415,0.1924±0.0240
3,Bank,90%,LightGBM,0.5073±0.0194,0.0347±0.0156,0.8821±0.0065,0.4064±0.1449,0.0181±0.0083
4,Blood,0%,LightGBM,0.7017±0.0964,0.4426±0.1441,0.7543±0.0697,0.4817±0.1746,0.4155±0.1554

In [ ]:
from google.colab import runtime
runtime.unassign()