In [1]:
import kagglehub
import pandas as pd
from sklearn.preprocessing import LabelEncoder

from experiment_utils import run_experiment

## Датасет [Bank](https://www.openml.org/search?type=data&id=1461&sort=runs&status=active)

In [2]:
dataset_id = 1461
res_bank = run_experiment(dataset_id=dataset_id)

[I 2025-04-20 22:14:35,252] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:14:42,023] Trial 0 finished with value: 0.894636975766192 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:14:52,399] Trial 1 finished with value: 0.8216458196929693 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:15:26,436] Trial 2 finished with value: 0.880421645251591 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:15:46,500] Trial 3 finished with value: 0.8872009949358448 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:15:59,471] Trial 4 finished with value: 0.8385927736487813 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:16:32,661] Trial 5 finished with value: 0.880421645251591 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:17:00,610] Trial 6 finished with value: 0.8929823788984221 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:17:10,709] Trial 7 finished with value: 0.8875432763479756 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:17:17,319] Trial 8 finished with value: 0.7975767612224985 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:17:30,906] Trial 9 finished with value: 0.8933275008201972 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.894636975766192.
[I 2025-04-20 22:17:37,585] Trial 10 finished with value: 0.895808685994441 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:17:44,258] Trial 11 finished with value: 0.895808685994441 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:17:50,961] Trial 12 finished with value: 0.895808685994441 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:17:57,537] Trial 13 finished with value: 0.8948599557732648 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:18:03,990] Trial 14 finished with value: 0.88825624426868 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:18:24,279] Trial 15 finished with value: 0.855016126993505 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:18:30,848] Trial 16 finished with value: 0.8948599557732648 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 10 with value: 0.895808685994441.
[I 2025-04-20 22:18:37,793] Trial 17 finished with value: 0.8961987826522502 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 17 with value: 0.8961987826522502.
[I 2025-04-20 22:18:44,345] Trial 18 finished with value: 0.8878670944474192 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 17 with value: 0.8961987826522502.
[I 2025-04-20 22:18:55,144] Trial 19 finished with value: 0.8933322350029375 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 17 with value: 0.8961987826522502.
[I 2025-04-20 22:19:06,536] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:19:26,827] Trial 0 finished with value: 0.716385527224628 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.716385527224628.
[I 2025-04-20 22:19:46,583] Trial 1 finished with value: 0.8289591851903402 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:19:53,415] Trial 2 finished with value: 0.7974681117286063 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:20:12,071] Trial 3 finished with value: 0.8204101979977246 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:20:45,880] Trial 4 finished with value: 0.7860968414953011 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:21:19,494] Trial 5 finished with value: 0.8097682286155781 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:21:40,432] Trial 6 finished with value: 0.7546770174838103 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:21:59,379] Trial 7 finished with value: 0.8201673344231422 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:22:18,384] Trial 8 finished with value: 0.8204101979977246 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:22:33,240] Trial 9 finished with value: 0.826109680598893 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:22:43,687] Trial 10 finished with value: 0.8233363963495662 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:22:58,051] Trial 11 finished with value: 0.826109680598893 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:23:13,038] Trial 12 finished with value: 0.826439653135899 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:23:25,816] Trial 13 finished with value: 0.7771558639717804 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:23:32,407] Trial 14 finished with value: 0.8150667259386346 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:23:42,872] Trial 15 finished with value: 0.8240711415108766 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:23:55,457] Trial 16 finished with value: 0.7775357821366975 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:24:11,248] Trial 17 finished with value: 0.8230480846206759 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:24:22,805] Trial 18 finished with value: 0.8233363963495662 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:24:55,005] Trial 19 finished with value: 0.8244815951544693 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.8289591851903402.
[I 2025-04-20 22:25:19,129] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:25:31,199] Trial 0 finished with value: 0.6062992088707222 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.6062992088707222.
[I 2025-04-20 22:25:46,976] Trial 1 finished with value: 0.631372860918706 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.631372860918706.
[I 2025-04-20 22:26:08,911] Trial 2 finished with value: 0.5659642086316461 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.631372860918706.
[I 2025-04-20 22:26:20,497] Trial 3 finished with value: 0.637860348237014 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 3 with value: 0.637860348237014.
[I 2025-04-20 22:26:57,681] Trial 4 finished with value: 0.591843855291183 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 3 with value: 0.637860348237014.
[I 2025-04-20 22:27:05,368] Trial 5 finished with value: 0.6336329597589733 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 3 with value: 0.637860348237014.
[I 2025-04-20 22:27:19,869] Trial 6 finished with value: 0.6305545574320279 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 3 with value: 0.637860348237014.
[I 2025-04-20 22:27:31,616] Trial 7 finished with value: 0.6366763291336398 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 3 with value: 0.637860348237014.
[I 2025-04-20 22:27:38,874] Trial 8 finished with value: 0.6399081189813742 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:27:46,098] Trial 9 finished with value: 0.6342017718152324 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:27:53,570] Trial 10 finished with value: 0.5641756343923227 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:28:05,348] Trial 11 finished with value: 0.6366763291336398 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:28:20,661] Trial 12 finished with value: 0.6120962156363428 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:28:39,150] Trial 13 finished with value: 0.6302333431330915 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:28:46,561] Trial 14 finished with value: 0.6321615757632568 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:28:58,283] Trial 15 finished with value: 0.6389458963393879 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:29:09,978] Trial 16 finished with value: 0.6389458963393879 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:29:17,119] Trial 17 finished with value: 0.6387882480541325 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:29:38,947] Trial 18 finished with value: 0.6074728127720675 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.6399081189813742.
[I 2025-04-20 22:29:54,882] Trial 19 finished with value: 0.6034546751711525 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 8 with value: 0.6399081189813742.

In [3]:
res_bank

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.8965±0.0065,0.4591±0.0212,0.8979±0.0044,0.6036±0.0276,0.3708±0.0206
1,0.5,0.8287±0.0090,0.3721±0.0229,0.8981±0.0045,0.6667±0.0342,0.2583±0.0189
2,0.9,0.6289±0.0126,0.0988±0.0170,0.8838±0.0047,0.5364±0.0697,0.0545±0.0099

## Датасет [Blood](https://www.openml.org/search?type=data&status=active&id=1464)

In [4]:
dataset_id = 1464
res_blood = run_experiment(dataset_id=dataset_id)

[I 2025-04-20 22:30:06,459] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:30:07,910] Trial 0 finished with value: 0.6159844054580897 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.6159844054580897.
[I 2025-04-20 22:30:08,350] Trial 1 finished with value: 0.6861598440545809 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:08,814] Trial 2 finished with value: 0.6413255360623782 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:09,170] Trial 3 finished with value: 0.6296296296296297 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:10,515] Trial 4 finished with value: 0.6393762183235868 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:10,974] Trial 5 finished with value: 0.6510721247563352 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:11,223] Trial 6 finished with value: 0.6734892787524367 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:11,502] Trial 7 finished with value: 0.6783625730994152 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:11,976] Trial 8 finished with value: 0.6539961013645225 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:12,617] Trial 9 finished with value: 0.6832358674463938 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:12,981] Trial 10 finished with value: 0.6676413255360624 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:13,626] Trial 11 finished with value: 0.6812865497076023 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:14,267] Trial 12 finished with value: 0.6783625730994152 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:14,907] Trial 13 finished with value: 0.6832358674463938 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:15,567] Trial 14 finished with value: 0.6598440545808968 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:16,016] Trial 15 finished with value: 0.6403508771929824 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:16,478] Trial 16 finished with value: 0.6861598440545809 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:16,938] Trial 17 finished with value: 0.6861598440545809 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:17,404] Trial 18 finished with value: 0.6861598440545809 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:17,880] Trial 19 finished with value: 0.6452241715399609 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.6861598440545809.
[I 2025-04-20 22:30:21,170] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:30:21,626] Trial 0 finished with value: 0.6705653021442495 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.6705653021442495.
[I 2025-04-20 22:30:22,088] Trial 1 finished with value: 0.5662768031189084 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.6705653021442495.
[I 2025-04-20 22:30:22,347] Trial 2 finished with value: 0.6764132553606238 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:22,708] Trial 3 finished with value: 0.6471734892787525 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:23,167] Trial 4 finished with value: 0.6150097465886939 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:23,518] Trial 5 finished with value: 0.6471734892787525 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:23,861] Trial 6 finished with value: 0.6666666666666667 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:25,116] Trial 7 finished with value: 0.550682261208577 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:25,581] Trial 8 finished with value: 0.6549707602339182 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:25,930] Trial 9 finished with value: 0.6306042884990253 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:26,204] Trial 10 finished with value: 0.6744639376218324 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:26,480] Trial 11 finished with value: 0.6744639376218324 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:26,753] Trial 12 finished with value: 0.6744639376218324 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:27,394] Trial 13 finished with value: 0.6101364522417154 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:27,694] Trial 14 finished with value: 0.6500974658869396 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:27,964] Trial 15 finished with value: 0.6705653021442496 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.6764132553606238.
[I 2025-04-20 22:30:28,248] Trial 16 finished with value: 0.682261208576998 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.682261208576998.
[I 2025-04-20 22:30:29,505] Trial 17 finished with value: 0.550682261208577 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 16 with value: 0.682261208576998.
[I 2025-04-20 22:30:30,112] Trial 18 finished with value: 0.5614035087719298 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 16 with value: 0.682261208576998.
[I 2025-04-20 22:30:30,391] Trial 19 finished with value: 0.682261208576998 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.682261208576998.
[I 2025-04-20 22:30:33,479] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:30:33,826] Trial 0 finished with value: 0.6739766081871345 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:34,248] Trial 1 finished with value: 0.6652046783625731 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:34,516] Trial 2 finished with value: 0.6369395711500975 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:34,910] Trial 3 finished with value: 0.6408382066276804 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:35,156] Trial 4 finished with value: 0.638888888888889 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:36,019] Trial 5 finished with value: 0.6642300194931774 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:37,132] Trial 6 finished with value: 0.6613060428849902 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:37,391] Trial 7 finished with value: 0.665204678362573 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:37,709] Trial 8 finished with value: 0.6632553606237817 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:38,007] Trial 9 finished with value: 0.6700779727095516 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:38,541] Trial 10 finished with value: 0.662280701754386 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:38,881] Trial 11 finished with value: 0.6622807017543859 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:39,222] Trial 12 finished with value: 0.638888888888889 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:39,518] Trial 13 finished with value: 0.6700779727095516 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:39,869] Trial 14 finished with value: 0.6622807017543859 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:40,396] Trial 15 finished with value: 0.6505847953216375 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:40,737] Trial 16 finished with value: 0.638888888888889 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.6739766081871345.
[I 2025-04-20 22:30:41,102] Trial 17 finished with value: 0.7012670565302144 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.7012670565302144.
[I 2025-04-20 22:30:41,446] Trial 18 finished with value: 0.7012670565302144 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.7012670565302144.
[I 2025-04-20 22:30:41,971] Trial 19 finished with value: 0.6661793372319688 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.7012670565302144.

In [5]:
res_blood

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.6517±0.0804,0.1968±0.1204,0.7875±0.0459,0.8700±0.3365,0.1142±0.0761
1,0.5,0.6830±0.0706,0.2605±0.1229,0.7860±0.0470,0.7399±0.2625,0.1641±0.0873
2,0.9,0.5766±0.0627,0.0000±0.0000,0.7599±0.0489,0.0000±0.0000,0.0000±0.0000

## Датасет [California](https://www.openml.org/search?type=data&status=active&id=44090)

In [6]:
dataset_id = 44090
res_california = run_experiment(dataset_id=dataset_id)

[I 2025-04-20 22:30:45,171] A new study created in memory with name: catboost_optimization_0.2

[I 2025-04-20 22:30:47,590] Trial 0 finished with value: 0.9377704164413196 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.9377704164413196.
[I 2025-04-20 22:30:49,549] Trial 1 finished with value: 0.8952009532179558 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.9377704164413196.
[I 2025-04-20 22:30:54,223] Trial 2 finished with value: 0.9470105837990507 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:30:58,259] Trial 3 finished with value: 0.9353958220659817 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:04,729] Trial 4 finished with value: 0.932476639024097 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:06,763] Trial 5 finished with value: 0.9408116624601885 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:09,132] Trial 6 finished with value: 0.9380962306952707 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:18,124] Trial 7 finished with value: 0.9432294483504597 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:21,396] Trial 8 finished with value: 0.9318644462472206 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:26,100] Trial 9 finished with value: 0.9440791944594676 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:30,720] Trial 10 finished with value: 0.8953385088035574 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:35,432] Trial 11 finished with value: 0.9440791944594676 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:40,150] Trial 12 finished with value: 0.9461420587705067 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:44,849] Trial 13 finished with value: 0.9461420587705067 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.9470105837990507.
[I 2025-04-20 22:31:48,154] Trial 14 finished with value: 0.9479673697494141 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:31:51,326] Trial 15 finished with value: 0.8811022099032509 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:31:54,640] Trial 16 finished with value: 0.9479673697494141 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:31:57,935] Trial 17 finished with value: 0.9479673697494141 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:32:01,229] Trial 18 finished with value: 0.9479673697494141 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:32:04,523] Trial 19 finished with value: 0.9456913647016406 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 14 with value: 0.9479673697494141.
[I 2025-04-20 22:32:11,481] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:32:14,756] Trial 0 finished with value: 0.8384900246379425 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8384900246379425.
[I 2025-04-20 22:32:23,729] Trial 1 finished with value: 0.844095532119464 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.844095532119464.
[I 2025-04-20 22:32:28,370] Trial 2 finished with value: 0.8478428655128898 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8478428655128898.
[I 2025-04-20 22:32:30,434] Trial 3 finished with value: 0.8545511650441681 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 3 with value: 0.8545511650441681.
[I 2025-04-20 22:32:39,519] Trial 4 finished with value: 0.8365736358992849 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 3 with value: 0.8545511650441681.
[I 2025-04-20 22:32:42,761] Trial 5 finished with value: 0.8577374782164533 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.8577374782164533.
[I 2025-04-20 22:32:47,425] Trial 6 finished with value: 0.842099332972778 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.8577374782164533.
[I 2025-04-20 22:32:52,070] Trial 7 finished with value: 0.8687315966588546 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 7 with value: 0.8687315966588546.
[I 2025-04-20 22:32:54,488] Trial 8 finished with value: 0.8514559296316326 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 7 with value: 0.8687315966588546.
[I 2025-04-20 22:32:59,148] Trial 9 finished with value: 0.8450091265548945 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 7 with value: 0.8687315966588546.
[I 2025-04-20 22:33:01,158] Trial 10 finished with value: 0.8529225632474011 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 7 with value: 0.8687315966588546.
[I 2025-04-20 22:33:04,451] Trial 11 finished with value: 0.8090024262364041 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 7 with value: 0.8687315966588546.
[I 2025-04-20 22:33:07,680] Trial 12 finished with value: 0.8708540840394208 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:10,142] Trial 13 finished with value: 0.8671292853494381 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:13,374] Trial 14 finished with value: 0.8708540840394208 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:16,631] Trial 15 finished with value: 0.8708540840394208 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:19,921] Trial 16 finished with value: 0.8090024262364041 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:23,181] Trial 17 finished with value: 0.8613139234421008 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 12 with value: 0.8708540840394208.
[I 2025-04-20 22:33:26,430] Trial 18 finished with value: 0.8723277597500151 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 18 with value: 0.8723277597500151.
[I 2025-04-20 22:33:29,680] Trial 19 finished with value: 0.8723277597500151 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 18 with value: 0.8723277597500151.
[I 2025-04-20 22:33:36,601] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:33:39,882] Trial 0 finished with value: 0.6440695233159065 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.6440695233159065.
[I 2025-04-20 22:33:42,156] Trial 1 finished with value: 0.6052586608376902 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.6440695233159065.
[I 2025-04-20 22:33:44,785] Trial 2 finished with value: 0.6480792921098492 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.6480792921098492.
[I 2025-04-20 22:33:47,434] Trial 3 finished with value: 0.6483694264166817 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:33:56,344] Trial 4 finished with value: 0.6191179729283096 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:05,227] Trial 5 finished with value: 0.631600790216934 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:13,694] Trial 6 finished with value: 0.6158987966468361 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:16,297] Trial 7 finished with value: 0.6480285890271016 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:20,835] Trial 8 finished with value: 0.6136204442341204 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:23,078] Trial 9 finished with value: 0.5985170287242353 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:25,736] Trial 10 finished with value: 0.646926735923322 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 3 with value: 0.6483694264166817.
[I 2025-04-20 22:34:28,445] Trial 11 finished with value: 0.6494604816417282 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:31,164] Trial 12 finished with value: 0.6494604816417282 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:33,893] Trial 13 finished with value: 0.6494604816417282 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:37,194] Trial 14 finished with value: 0.6450732565651103 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:41,730] Trial 15 finished with value: 0.6272173209242232 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:44,441] Trial 16 finished with value: 0.6442868893095367 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:47,153] Trial 17 finished with value: 0.6494604816417282 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 11 with value: 0.6494604816417282.
[I 2025-04-20 22:34:49,889] Trial 18 finished with value: 0.6511458896700919 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 18 with value: 0.6511458896700919.
[I 2025-04-20 22:34:54,432] Trial 19 finished with value: 0.6459953015143322 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 18 with value: 0.6511458896700919.

In [7]:
res_california

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.9365±0.0048,0.8553±0.0081,0.8548±0.0076,0.8524±0.0106,0.8584±0.0107
1,0.5,0.8560±0.0080,0.7661±0.0101,0.7667±0.0093,0.7681±0.0127,0.7643±0.0128
2,0.9,0.6451±0.0115,0.6477±0.0110,0.5709±0.0111,0.5495±0.0127,0.7887±0.0128

## Датасет [Car](https://www.openml.org/search?type=data&id=40975&sort=runs&status=active)

In [8]:
dataset_id = 40975
res_car = run_experiment(dataset_id=dataset_id, multi=True)

[I 2025-04-20 22:35:00,848] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:35:05,420] Trial 0 finished with value: 0.8713201128337089 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8713201128337089.
[I 2025-04-20 22:35:07,197] Trial 1 finished with value: 0.8183132221298257 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.8713201128337089.
[I 2025-04-20 22:35:25,586] Trial 2 finished with value: 0.9118403398194872 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.9118403398194872.
[I 2025-04-20 22:35:26,626] Trial 3 finished with value: 0.9026215455501598 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.9118403398194872.
[I 2025-04-20 22:35:29,381] Trial 4 finished with value: 0.8707926797360364 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.9118403398194872.
[I 2025-04-20 22:35:47,313] Trial 5 finished with value: 0.9207350488187831 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 5 with value: 0.9207350488187831.
[I 2025-04-20 22:35:53,820] Trial 6 finished with value: 0.9145218148573215 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.9207350488187831.
[I 2025-04-20 22:35:55,832] Trial 7 finished with value: 0.9132006881274799 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 5 with value: 0.9207350488187831.
[I 2025-04-20 22:36:13,327] Trial 8 finished with value: 0.9233382711321371 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 8 with value: 0.9233382711321371.
[I 2025-04-20 22:36:14,349] Trial 9 finished with value: 0.9401708393459038 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:15,403] Trial 10 finished with value: 0.9142302696042565 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:19,744] Trial 11 finished with value: 0.9309809853767284 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:24,072] Trial 12 finished with value: 0.9309809853767284 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:28,326] Trial 13 finished with value: 0.9309809853767284 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:32,526] Trial 14 finished with value: 0.9280558319836784 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:33,576] Trial 15 finished with value: 0.9401708393459038 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:34,610] Trial 16 finished with value: 0.9401708393459038 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:35,635] Trial 17 finished with value: 0.9401708393459038 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:36,690] Trial 18 finished with value: 0.9401708393459038 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:37,736] Trial 19 finished with value: 0.9291742540799469 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 9 with value: 0.9401708393459038.
[I 2025-04-20 22:36:42,221] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:36:44,268] Trial 0 finished with value: 0.7639394362633762 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.7639394362633762.
[I 2025-04-20 22:36:46,342] Trial 1 finished with value: 0.7747713171277233 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.7747713171277233.
[I 2025-04-20 22:36:50,294] Trial 2 finished with value: 0.7948140954772378 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:36:52,846] Trial 3 finished with value: 0.7602116235321117 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:36:56,966] Trial 4 finished with value: 0.7882654953876053 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:37:11,012] Trial 5 finished with value: 0.779812766402922 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:37:28,581] Trial 6 finished with value: 0.7554074389259777 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:37:32,844] Trial 7 finished with value: 0.7787434029308831 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.7948140954772378.
[I 2025-04-20 22:37:34,894] Trial 8 finished with value: 0.7991847349367545 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:36,965] Trial 9 finished with value: 0.7868258997134941 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:38,031] Trial 10 finished with value: 0.7938201675973788 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:41,926] Trial 11 finished with value: 0.7883515883041478 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:42,998] Trial 12 finished with value: 0.7987665334128278 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:44,070] Trial 13 finished with value: 0.7987665334128278 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:45,135] Trial 14 finished with value: 0.7987665334128278 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:51,092] Trial 15 finished with value: 0.7738242924094421 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:53,181] Trial 16 finished with value: 0.7991847349367545 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:54,898] Trial 17 finished with value: 0.7358725887531818 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:56,963] Trial 18 finished with value: 0.7991847349367545 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:37:59,008] Trial 19 finished with value: 0.7991847349367545 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.7991847349367545.
[I 2025-04-20 22:38:04,541] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:38:05,637] Trial 0 finished with value: 0.604343268742078 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.604343268742078.
[I 2025-04-20 22:38:07,094] Trial 1 finished with value: 0.5897298374554326 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.604343268742078.
[I 2025-04-20 22:38:11,583] Trial 2 finished with value: 0.5680152556718214 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.604343268742078.
[I 2025-04-20 22:38:18,944] Trial 3 finished with value: 0.566997324746116 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.604343268742078.
[I 2025-04-20 22:38:19,930] Trial 4 finished with value: 0.6259025783871719 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 4 with value: 0.6259025783871719.
[I 2025-04-20 22:38:37,582] Trial 5 finished with value: 0.505912628559609 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 4 with value: 0.6259025783871719.
[I 2025-04-20 22:38:43,480] Trial 6 finished with value: 0.6305292585869265 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:38:47,983] Trial 7 finished with value: 0.5791072716675408 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:38:49,104] Trial 8 finished with value: 0.590932799347001 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:38:51,583] Trial 9 finished with value: 0.6010229513652499 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:38:57,457] Trial 10 finished with value: 0.6305292585869265 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:03,333] Trial 11 finished with value: 0.6305292585869265 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:09,211] Trial 12 finished with value: 0.6305292585869265 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:15,015] Trial 13 finished with value: 0.6192343649959672 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:20,905] Trial 14 finished with value: 0.6305292585869265 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:23,149] Trial 15 finished with value: 0.6237524202631824 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 6 with value: 0.6305292585869265.
[I 2025-04-20 22:39:30,282] Trial 16 finished with value: 0.6402569507090967 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.6402569507090967.
[I 2025-04-20 22:39:37,312] Trial 17 finished with value: 0.5564976891923533 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 16 with value: 0.6402569507090967.
[I 2025-04-20 22:39:44,432] Trial 18 finished with value: 0.6402569507090967 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.6402569507090967.
[I 2025-04-20 22:39:46,629] Trial 19 finished with value: 0.6319402764773017 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.6402569507090967.

In [9]:
res_car

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.9350±0.0137,0.4961±0.0580,0.7742±0.0307,0.5320±0.0716,0.4998±0.0570
1,0.5,0.8228±0.0315,0.2959±0.0229,0.7352±0.0327,0.3291±0.0324,0.3042±0.0177
2,0.9,0.5259±0.0372,0.2025±0.0063,0.6815±0.0353,0.1735±0.0087,0.2436±0.0037

## Датасет [Credit-g](https://www.openml.org/search?type=data&status=active&id=31)

In [10]:
dataset_id = 31
res_creditg = run_experiment(dataset_id=dataset_id)

[I 2025-04-20 22:39:57,203] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:39:58,219] Trial 0 finished with value: 0.7780952380952381 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:01,296] Trial 1 finished with value: 0.7238095238095239 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:10,001] Trial 2 finished with value: 0.7461904761904762 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:18,597] Trial 3 finished with value: 0.7461904761904762 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:19,631] Trial 4 finished with value: 0.7561904761904761 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:27,904] Trial 5 finished with value: 0.7742857142857142 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:32,953] Trial 6 finished with value: 0.7695238095238096 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:36,036] Trial 7 finished with value: 0.7476190476190476 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:39,086] Trial 8 finished with value: 0.7238095238095239 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.7780952380952381.
[I 2025-04-20 22:40:40,092] Trial 9 finished with value: 0.7919047619047619 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 9 with value: 0.7919047619047619.
[I 2025-04-20 22:40:42,086] Trial 10 finished with value: 0.7514285714285714 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 9 with value: 0.7919047619047619.
[I 2025-04-20 22:40:43,081] Trial 11 finished with value: 0.7971428571428572 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:44,099] Trial 12 finished with value: 0.7971428571428572 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:45,104] Trial 13 finished with value: 0.7971428571428572 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:46,106] Trial 14 finished with value: 0.7971428571428572 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:52,450] Trial 15 finished with value: 0.7761904761904762 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:54,095] Trial 16 finished with value: 0.7652380952380952 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:55,036] Trial 17 finished with value: 0.7804761904761904 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:56,049] Trial 18 finished with value: 0.7971428571428572 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:40:57,007] Trial 19 finished with value: 0.7609523809523809 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 11 with value: 0.7971428571428572.
[I 2025-04-20 22:41:00,846] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:41:03,832] Trial 0 finished with value: 0.7019047619047619 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.7019047619047619.
[I 2025-04-20 22:41:05,688] Trial 1 finished with value: 0.7219047619047619 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.7219047619047619.
[I 2025-04-20 22:41:07,648] Trial 2 finished with value: 0.6776190476190476 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.7219047619047619.
[I 2025-04-20 22:41:14,263] Trial 3 finished with value: 0.7361904761904763 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 3 with value: 0.7361904761904763.
[I 2025-04-20 22:41:16,186] Trial 4 finished with value: 0.740952380952381 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:19,089] Trial 5 finished with value: 0.7204761904761904 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:20,045] Trial 6 finished with value: 0.729047619047619 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:23,133] Trial 7 finished with value: 0.6838095238095238 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:24,101] Trial 8 finished with value: 0.7004761904761905 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:30,326] Trial 9 finished with value: 0.6904761904761905 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:32,007] Trial 10 finished with value: 0.7376190476190476 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:33,662] Trial 11 finished with value: 0.7376190476190476 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:35,308] Trial 12 finished with value: 0.7376190476190476 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:37,213] Trial 13 finished with value: 0.5861904761904762 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:45,745] Trial 14 finished with value: 0.7304761904761905 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.740952380952381.
[I 2025-04-20 22:41:51,583] Trial 15 finished with value: 0.7471428571428571 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7471428571428571.
[I 2025-04-20 22:41:57,642] Trial 16 finished with value: 0.7357142857142858 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 15 with value: 0.7471428571428571.
[I 2025-04-20 22:42:03,586] Trial 17 finished with value: 0.7276190476190475 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 15 with value: 0.7471428571428571.
[I 2025-04-20 22:42:09,573] Trial 18 finished with value: 0.7328571428571429 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 15 with value: 0.7471428571428571.
[I 2025-04-20 22:42:15,401] Trial 19 finished with value: 0.7471428571428571 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7471428571428571.
[I 2025-04-20 22:42:24,039] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:42:27,077] Trial 0 finished with value: 0.4238095238095238 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.4238095238095238.
[I 2025-04-20 22:42:28,147] Trial 1 finished with value: 0.4483333333333333 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.4483333333333333.
[I 2025-04-20 22:42:29,190] Trial 2 finished with value: 0.46928571428571425 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.46928571428571425.
[I 2025-04-20 22:42:32,303] Trial 3 finished with value: 0.4804761904761905 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 3 with value: 0.4804761904761905.
[I 2025-04-20 22:42:40,473] Trial 4 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:42:42,379] Trial 5 finished with value: 0.440952380952381 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:42:44,372] Trial 6 finished with value: 0.4004761904761905 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:42:48,393] Trial 7 finished with value: 0.44428571428571423 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:42:54,316] Trial 8 finished with value: 0.4757142857142857 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:42:57,364] Trial 9 finished with value: 0.41904761904761906 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:05,845] Trial 10 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:13,756] Trial 11 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:21,614] Trial 12 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:29,476] Trial 13 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:37,364] Trial 14 finished with value: 0.48142857142857143 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:42,780] Trial 15 finished with value: 0.4285714285714285 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:46,543] Trial 16 finished with value: 0.38761904761904764 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.48142857142857143.
[I 2025-04-20 22:43:54,181] Trial 17 finished with value: 0.4828571428571429 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.4828571428571429.
[I 2025-04-20 22:44:01,827] Trial 18 finished with value: 0.4828571428571429 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.4828571428571429.
[I 2025-04-20 22:44:03,803] Trial 19 finished with value: 0.4257142857142857 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 17 with value: 0.4828571428571429.

In [11]:
res_creditg

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.7829±0.0503,0.8574±0.0311,0.7792±0.0426,0.7776±0.0461,0.9576±0.0238
1,0.5,0.6577±0.0602,0.8361±0.0325,0.7396±0.0447,0.7433±0.0472,0.9577±0.0250
2,0.9,0.5225±0.0606,0.7701±0.0371,0.6394±0.0476,0.6924±0.0502,0.8707±0.0404

## Датасет [Diabets](https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database)

In [12]:
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database") + "/diabetes.csv"
df = pd.read_csv(path)
df.head()
X = df.drop(columns=["Outcome"])
y = df["Outcome"]
le = LabelEncoder()
y = le.fit_transform(y)
categorical_features = []

res_diabets = run_experiment(X=X, y=y, categorical_features=categorical_features)

[I 2025-04-20 22:44:14,854] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:44:15,448] Trial 0 finished with value: 0.8318518518518518 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8318518518518518.
[I 2025-04-20 22:44:15,910] Trial 1 finished with value: 0.8822222222222222 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.8822222222222222.
[I 2025-04-20 22:44:18,672] Trial 2 finished with value: 0.905925925925926 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.905925925925926.
[I 2025-04-20 22:44:19,135] Trial 3 finished with value: 0.9029629629629629 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.905925925925926.
[I 2025-04-20 22:44:19,587] Trial 4 finished with value: 0.8637037037037038 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.905925925925926.
[I 2025-04-20 22:44:20,211] Trial 5 finished with value: 0.8733333333333333 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.905925925925926.
[I 2025-04-20 22:44:23,003] Trial 6 finished with value: 0.9037037037037038 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.905925925925926.
[I 2025-04-20 22:44:25,555] Trial 7 finished with value: 0.9118518518518518 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 7 with value: 0.9118518518518518.
[I 2025-04-20 22:44:26,023] Trial 8 finished with value: 0.8822222222222222 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 7 with value: 0.9118518518518518.
[I 2025-04-20 22:44:27,104] Trial 9 finished with value: 0.9155555555555556 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:28,183] Trial 10 finished with value: 0.8866666666666667 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:28,482] Trial 11 finished with value: 0.8703703703703703 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:29,563] Trial 12 finished with value: 0.9066666666666666 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:30,629] Trial 13 finished with value: 0.902962962962963 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:33,117] Trial 14 finished with value: 0.8622222222222222 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:33,410] Trial 15 finished with value: 0.8940740740740741 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:34,488] Trial 16 finished with value: 0.9155555555555556 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:35,585] Trial 17 finished with value: 0.9155555555555556 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:36,669] Trial 18 finished with value: 0.9155555555555556 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:37,747] Trial 19 finished with value: 0.9155555555555556 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 9 with value: 0.9155555555555556.
[I 2025-04-20 22:44:41,616] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:44:42,661] Trial 0 finished with value: 0.8162962962962963 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.8162962962962963.
[I 2025-04-20 22:44:43,708] Trial 1 finished with value: 0.7414814814814814 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.8162962962962963.
[I 2025-04-20 22:44:44,159] Trial 2 finished with value: 0.8540740740740741 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:45,136] Trial 3 finished with value: 0.6911111111111111 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:45,457] Trial 4 finished with value: 0.8392592592592591 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:45,745] Trial 5 finished with value: 0.8355555555555555 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:46,037] Trial 6 finished with value: 0.7948148148148149 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:48,622] Trial 7 finished with value: 0.7651851851851852 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:49,589] Trial 8 finished with value: 0.7237037037037036 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:52,232] Trial 9 finished with value: 0.7518518518518518 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:52,682] Trial 10 finished with value: 0.8414814814814815 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:53,133] Trial 11 finished with value: 0.8414814814814815 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:53,578] Trial 12 finished with value: 0.8414814814814815 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:54,200] Trial 13 finished with value: 0.7281481481481482 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:54,650] Trial 14 finished with value: 0.8414814814814815 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:55,110] Trial 15 finished with value: 0.7762962962962963 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:55,563] Trial 16 finished with value: 0.8540740740740741 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:56,188] Trial 17 finished with value: 0.7681481481481481 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:56,626] Trial 18 finished with value: 0.797037037037037 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:44:57,079] Trial 19 finished with value: 0.8540740740740741 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.8540740740740741.
[I 2025-04-20 22:45:00,325] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:45:01,042] Trial 0 finished with value: 0.5688888888888889 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.5688888888888889.
[I 2025-04-20 22:45:01,743] Trial 1 finished with value: 0.5318518518518518 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.5688888888888889.
[I 2025-04-20 22:45:02,064] Trial 2 finished with value: 0.5866666666666667 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.5866666666666667.
[I 2025-04-20 22:45:02,790] Trial 3 finished with value: 0.6022222222222222 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 3 with value: 0.6022222222222222.
[I 2025-04-20 22:45:03,198] Trial 4 finished with value: 0.5822222222222222 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 3 with value: 0.6022222222222222.
[I 2025-04-20 22:45:03,725] Trial 5 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:04,254] Trial 6 finished with value: 0.5548148148148148 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:05,763] Trial 7 finished with value: 0.5518518518518518 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:06,062] Trial 8 finished with value: 0.5155555555555555 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:06,586] Trial 9 finished with value: 0.597037037037037 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:07,117] Trial 10 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:07,630] Trial 11 finished with value: 0.5518518518518518 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:08,161] Trial 12 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:08,686] Trial 13 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:10,187] Trial 14 finished with value: 0.5548148148148149 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:10,557] Trial 15 finished with value: 0.6 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:11,085] Trial 16 finished with value: 0.5525925925925926 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:11,621] Trial 17 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:12,147] Trial 18 finished with value: 0.6103703703703703 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.
[I 2025-04-20 22:45:12,451] Trial 19 finished with value: 0.5518518518518518 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.6103703703703703.

In [13]:
res_diabets

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.7790±0.0570,0.5364±0.0916,0.7396±0.0505,0.7005±0.1164,0.4416±0.0947
1,0.5,0.6384±0.0669,0.4073±0.0954,0.6744±0.0533,0.5550±0.1262,0.3287±0.0916
2,0.9,0.3984±0.0697,0.1631±0.0882,0.6122±0.0561,0.3307±0.1739,0.1117±0.0646

## Датасет [Heart](https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction)

In [14]:
path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction") + "/heart.csv"

df = pd.read_csv(path)
df.head()

X = df.drop(columns=["HeartDisease"])
y = df["HeartDisease"]
le = LabelEncoder()
y = le.fit_transform(y)
categorical_features = ["Sex", "ChestPainType", "FastingBS", "RestingECG", "ExerciseAngina", "ST_Slope"]

res_heart = run_experiment(X=X, y=y, categorical_features=categorical_features)

[I 2025-04-20 22:45:16,209] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:45:17,767] Trial 0 finished with value: 0.9057867049258728 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.9057867049258728.
[I 2025-04-20 22:45:18,487] Trial 1 finished with value: 0.9258727881396461 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:21,034] Trial 2 finished with value: 0.9014825442372071 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:22,307] Trial 3 finished with value: 0.9110473457675753 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:23,043] Trial 4 finished with value: 0.910569105691057 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:25,607] Trial 5 finished with value: 0.9043519846963176 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:27,411] Trial 6 finished with value: 0.90961262553802 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.9258727881396461.
[I 2025-04-20 22:45:28,179] Trial 7 finished with value: 0.9277857484457198 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:29,958] Trial 8 finished with value: 0.9081779053084649 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:30,698] Trial 9 finished with value: 0.8852223816355811 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:34,536] Trial 10 finished with value: 0.9038737446197991 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:35,244] Trial 11 finished with value: 0.9239598278335726 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:35,976] Trial 12 finished with value: 0.9258727881396461 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:36,686] Trial 13 finished with value: 0.9258727881396461 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:37,924] Trial 14 finished with value: 0.9033955045432808 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:42,162] Trial 15 finished with value: 0.8962219033955046 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 7 with value: 0.9277857484457198.
[I 2025-04-20 22:45:42,917] Trial 16 finished with value: 0.9287422285987565 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.9287422285987565.
[I 2025-04-20 22:45:43,655] Trial 17 finished with value: 0.9287422285987565 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.9287422285987565.
[I 2025-04-20 22:45:44,399] Trial 18 finished with value: 0.9287422285987565 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.9287422285987565.
[I 2025-04-20 22:45:47,022] Trial 19 finished with value: 0.8990913438546151 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 16 with value: 0.9287422285987565.
[I 2025-04-20 22:45:50,560] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:45:52,080] Trial 0 finished with value: 0.8091822094691534 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.8091822094691534.
[I 2025-04-20 22:45:52,863] Trial 1 finished with value: 0.8010521281683406 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.8091822094691534.
[I 2025-04-20 22:45:53,577] Trial 2 finished with value: 0.8263988522238165 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.8263988522238165.
[I 2025-04-20 22:45:57,765] Trial 3 finished with value: 0.8187470109995219 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.8263988522238165.
[I 2025-04-20 22:45:58,896] Trial 4 finished with value: 0.8144428503108561 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.8263988522238165.
[I 2025-04-20 22:46:01,225] Trial 5 finished with value: 0.8134863701578192 and parameters: {'depth': 8, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.8263988522238165.
[I 2025-04-20 22:46:01,883] Trial 6 finished with value: 0.7914873266379722 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.8263988522238165.
[I 2025-04-20 22:46:04,335] Trial 7 finished with value: 0.8354854136776662 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 7 with value: 0.8354854136776662.
[I 2025-04-20 22:46:08,594] Trial 8 finished with value: 0.8627450980392156 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:09,853] Trial 9 finished with value: 0.8230511716881875 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:14,328] Trial 10 finished with value: 0.8536585365853658 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:18,783] Trial 11 finished with value: 0.8536585365853658 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:23,238] Trial 12 finished with value: 0.8536585365853658 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:27,362] Trial 13 finished with value: 0.8024868483978957 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:31,838] Trial 14 finished with value: 0.8436154949784792 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:33,519] Trial 15 finished with value: 0.8278335724533716 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:37,975] Trial 16 finished with value: 0.8536585365853658 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:42,029] Trial 17 finished with value: 0.76805356288857 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:46,554] Trial 18 finished with value: 0.8608321377331419 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:49,029] Trial 19 finished with value: 0.8397895743663318 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 8 with value: 0.8627450980392156.
[I 2025-04-20 22:46:56,076] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:46:57,749] Trial 0 finished with value: 0.631037780966045 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.631037780966045.
[I 2025-04-20 22:47:01,272] Trial 1 finished with value: 0.6855571496891439 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.6855571496891439.
[I 2025-04-20 22:47:03,541] Trial 2 finished with value: 0.6936872309899571 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:05,175] Trial 3 finished with value: 0.6865136298421808 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:06,499] Trial 4 finished with value: 0.6697752271640363 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:08,166] Trial 5 finished with value: 0.6922525107604017 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:09,371] Trial 6 finished with value: 0.6850789096126255 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:11,101] Trial 7 finished with value: 0.631037780966045 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.6936872309899571.
[I 2025-04-20 22:47:11,875] Trial 8 finished with value: 0.6963175514108082 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 8 with value: 0.6963175514108082.
[I 2025-04-20 22:47:13,096] Trial 9 finished with value: 0.7008608321377331 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 9 with value: 0.7008608321377331.
[I 2025-04-20 22:47:14,370] Trial 10 finished with value: 0.6750358680057389 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 9 with value: 0.7008608321377331.
[I 2025-04-20 22:47:15,115] Trial 11 finished with value: 0.6857962697274032 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 9 with value: 0.7008608321377331.
[I 2025-04-20 22:47:15,890] Trial 12 finished with value: 0.6963175514108082 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 1.0}. Best is trial 9 with value: 0.7008608321377331.
[I 2025-04-20 22:47:16,635] Trial 13 finished with value: 0.7140124342419895 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 13 with value: 0.7140124342419895.
[I 2025-04-20 22:47:20,844] Trial 14 finished with value: 0.7190339550454328 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.
[I 2025-04-20 22:47:25,062] Trial 15 finished with value: 0.7190339550454328 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.
[I 2025-04-20 22:47:29,285] Trial 16 finished with value: 0.7190339550454328 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.
[I 2025-04-20 22:47:33,499] Trial 17 finished with value: 0.7190339550454328 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.
[I 2025-04-20 22:47:37,746] Trial 18 finished with value: 0.7190339550454328 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.
[I 2025-04-20 22:47:42,205] Trial 19 finished with value: 0.6396461023433764 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 14 with value: 0.7190339550454328.

In [15]:
res_heart

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.9193±0.0272,0.8408±0.0393,0.8370±0.0367,0.9087±0.0429,0.7847±0.0559
1,0.5,0.8635±0.0370,0.7714±0.0467,0.7710±0.0423,0.8577±0.0548,0.7039±0.0609
2,0.9,0.5888±0.0592,0.6355±0.0530,0.5433±0.0529,0.5693±0.0615,0.7244±0.0646

## Датасет [Income](https://www.openml.org/search?type=data&status=active&id=1590)

In [16]:
dataset_id = 1590
res_income = run_experiment(dataset_id=dataset_id)

[I 2025-04-20 22:47:49,281] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 22:48:18,143] Trial 0 finished with value: 0.8788861612466288 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.8788861612466288.
[I 2025-04-20 22:48:28,676] Trial 1 finished with value: 0.908287837672341 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:48:48,739] Trial 2 finished with value: 0.8723398965562646 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:49:07,435] Trial 3 finished with value: 0.9035058439172707 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:49:17,804] Trial 4 finished with value: 0.9009440368839439 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:49:45,707] Trial 5 finished with value: 0.8869112459380792 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:49:52,536] Trial 6 finished with value: 0.859514977426356 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:49:59,709] Trial 7 finished with value: 0.907966014764259 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:50:14,341] Trial 8 finished with value: 0.906842166812001 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:50:21,620] Trial 9 finished with value: 0.9017700029742146 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.908287837672341.
[I 2025-04-20 22:50:32,171] Trial 10 finished with value: 0.9084248080802874 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 10 with value: 0.9084248080802874.
[I 2025-04-20 22:50:42,704] Trial 11 finished with value: 0.9084248080802874 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 10 with value: 0.9084248080802874.
[I 2025-04-20 22:50:53,261] Trial 12 finished with value: 0.9084248080802874 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 10 with value: 0.9084248080802874.
[I 2025-04-20 22:51:03,879] Trial 13 finished with value: 0.9084248080802874 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 10 with value: 0.9084248080802874.
[I 2025-04-20 22:51:14,409] Trial 14 finished with value: 0.9084248080802874 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 10 with value: 0.9084248080802874.
[I 2025-04-20 22:51:28,848] Trial 15 finished with value: 0.9087537672617245 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.9087537672617245.
[I 2025-04-20 22:51:43,241] Trial 16 finished with value: 0.9082604435907518 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 15 with value: 0.9087537672617245.
[I 2025-04-20 22:51:57,730] Trial 17 finished with value: 0.9088016493539142 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 17 with value: 0.9088016493539142.
[I 2025-04-20 22:52:12,375] Trial 18 finished with value: 0.8991732051812107 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 17 with value: 0.9088016493539142.
[I 2025-04-20 22:52:25,209] Trial 19 finished with value: 0.882453262013571 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 17 with value: 0.9088016493539142.
[I 2025-04-20 22:52:44,274] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 22:53:03,947] Trial 0 finished with value: 0.8701215514534518 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.8701215514534518.
[I 2025-04-20 22:53:24,035] Trial 1 finished with value: 0.8291786793934811 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8701215514534518.
[I 2025-04-20 22:53:52,551] Trial 2 finished with value: 0.8660957724716645 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8701215514534518.
[I 2025-04-20 22:53:59,492] Trial 3 finished with value: 0.8522534739839097 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.8701215514534518.
[I 2025-04-20 22:54:10,701] Trial 4 finished with value: 0.8704756026928153 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:54:29,480] Trial 5 finished with value: 0.8673393256543963 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:54:40,035] Trial 6 finished with value: 0.8622902971544226 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:55:11,410] Trial 7 finished with value: 0.8609997826889663 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:55:39,488] Trial 8 finished with value: 0.8481638138454752 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:55:46,398] Trial 9 finished with value: 0.8522534739839097 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:55:57,666] Trial 10 finished with value: 0.8704756026928153 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:56:08,894] Trial 11 finished with value: 0.8704756026928153 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:56:23,743] Trial 12 finished with value: 0.8593856036964975 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 1.0}. Best is trial 4 with value: 0.8704756026928153.
[I 2025-04-20 22:56:35,023] Trial 13 finished with value: 0.8723409324669129 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:56:46,274] Trial 14 finished with value: 0.8723409324669129 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:56:56,197] Trial 15 finished with value: 0.835144949221962 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:57:11,071] Trial 16 finished with value: 0.8715322315541145 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:57:22,341] Trial 17 finished with value: 0.8708920387734449 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:57:34,075] Trial 18 finished with value: 0.8723409324669129 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:57:45,319] Trial 19 finished with value: 0.8723409324669129 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 13 with value: 0.8723409324669129.
[I 2025-04-20 22:58:00,936] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 22:58:08,174] Trial 0 finished with value: 0.706876420924106 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:58:23,879] Trial 1 finished with value: 0.6754864866606938 and parameters: {'depth': 6, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:58:38,604] Trial 2 finished with value: 0.70604550548296 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:58:45,705] Trial 3 finished with value: 0.705579921197126 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:58:59,228] Trial 4 finished with value: 0.6825142196001662 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:59:06,845] Trial 5 finished with value: 0.7038165710712974 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:59:13,941] Trial 6 finished with value: 0.7064709194558753 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 22:59:34,633] Trial 7 finished with value: 0.6881306969330598 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:12,483] Trial 8 finished with value: 0.6498855664037142 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:23,949] Trial 9 finished with value: 0.6991192917870241 and parameters: {'depth': 4, 'learning_rate': 0.3, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:35,518] Trial 10 finished with value: 0.7060422826498318 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:42,580] Trial 11 finished with value: 0.6941355256578954 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:49,631] Trial 12 finished with value: 0.6506288898444845 and parameters: {'depth': 2, 'learning_rate': 0.001, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:00:57,008] Trial 13 finished with value: 0.7052614362233551 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:01:34,841] Trial 14 finished with value: 0.6847887340803553 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:01:55,415] Trial 15 finished with value: 0.7049057735674277 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:02:02,498] Trial 16 finished with value: 0.7064709194558753 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:02:09,538] Trial 17 finished with value: 0.706876420924106 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:02:16,589] Trial 18 finished with value: 0.706876420924106 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.
[I 2025-04-20 23:02:37,194] Trial 19 finished with value: 0.6881306969330598 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.706876420924106.

In [17]:
res_income

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.9171±0.0042,0.6906±0.0113,0.8646±0.0048,0.7622±0.0133,0.6316±0.0142
1,0.5,0.8748±0.0054,0.6004±0.0127,0.8342±0.0054,0.7096±0.0147,0.5206±0.0148
2,0.9,0.6987±0.0083,0.2027±0.0140,0.7722±0.0059,0.6250±0.0316,0.1211±0.0092

## Датасет [Jungle](https://www.openml.org/search?type=data&status=active&id=41027)

In [18]:
dataset_id = 41027
res_jungle = run_experiment(dataset_id=dataset_id, multi=True)

[I 2025-04-20 23:02:48,834] A new study created in memory with name: catboost_optimization_0.2
[I 2025-04-20 23:02:51,405] Trial 0 finished with value: 0.8950148702956481 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 0 with value: 0.8950148702956481.
[I 2025-04-20 23:02:53,392] Trial 1 finished with value: 0.8661645332629236 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.8950148702956481.
[I 2025-04-20 23:02:55,975] Trial 2 finished with value: 0.8949773919496637 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.8950148702956481.
[I 2025-04-20 23:03:01,186] Trial 3 finished with value: 0.8683517598641357 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.8950148702956481.
[I 2025-04-20 23:03:06,444] Trial 4 finished with value: 0.8918887800796274 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 0 with value: 0.8950148702956481.
[I 2025-04-20 23:03:11,690] Trial 5 finished with value: 0.8960866435744723 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:13,667] Trial 6 finished with value: 0.8407581097268771 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:17,709] Trial 7 finished with value: 0.889915489331227 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:19,699] Trial 8 finished with value: 0.8407061259044526 and parameters: {'depth': 2, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:22,216] Trial 9 finished with value: 0.7822495547867091 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:25,453] Trial 10 finished with value: 0.8038175091866603 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:28,056] Trial 11 finished with value: 0.8950148702956481 and parameters: {'depth': 4, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:33,251] Trial 12 finished with value: 0.8752296866289413 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:36,530] Trial 13 finished with value: 0.878157857931753 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 5 with value: 0.8960866435744723.
[I 2025-04-20 23:03:40,561] Trial 14 finished with value: 0.8969211658306412 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 14 with value: 0.8969211658306412.
[I 2025-04-20 23:03:44,570] Trial 15 finished with value: 0.8969211658306412 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 14 with value: 0.8969211658306412.
[I 2025-04-20 23:03:48,557] Trial 16 finished with value: 0.8969211658306412 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 14 with value: 0.8969211658306412.
[I 2025-04-20 23:03:52,574] Trial 17 finished with value: 0.8969211658306412 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 14 with value: 0.8969211658306412.
[I 2025-04-20 23:03:56,629] Trial 18 finished with value: 0.8969211658306412 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 14 with value: 0.8969211658306412.
[I 2025-04-20 23:04:00,625] Trial 19 finished with value: 0.8972176934627735 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 19 with value: 0.8972176934627735.
[I 2025-04-20 23:04:11,181] A new study created in memory with name: catboost_optimization_0.5
[I 2025-04-20 23:04:17,040] Trial 0 finished with value: 0.779358741709407 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 0 with value: 0.779358741709407.
[I 2025-04-20 23:04:21,557] Trial 1 finished with value: 0.7815209249499883 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:27,240] Trial 2 finished with value: 0.743798447857945 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:31,800] Trial 3 finished with value: 0.7804397779629779 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:37,541] Trial 4 finished with value: 0.7741746833997362 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:40,257] Trial 5 finished with value: 0.7765157826429396 and parameters: {'depth': 4, 'learning_rate': 0.03, 'l2_leaf_reg': 0.001}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:44,822] Trial 6 finished with value: 0.7784407943995069 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 3.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:46,895] Trial 7 finished with value: 0.77519776192378 and parameters: {'depth': 2, 'learning_rate': 0.3, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:48,919] Trial 8 finished with value: 0.7373638954384721 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:51,614] Trial 9 finished with value: 0.7591266684060863 and parameters: {'depth': 4, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:54,967] Trial 10 finished with value: 0.730924976227512 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:04:59,425] Trial 11 finished with value: 0.7658430452796092 and parameters: {'depth': 8, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 1 with value: 0.7815209249499883.
[I 2025-04-20 23:05:03,973] Trial 12 finished with value: 0.7816811185704035 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1.0}. Best is trial 12 with value: 0.7816811185704035.
[I 2025-04-20 23:05:08,511] Trial 13 finished with value: 0.7815209249499883 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 3.0}. Best is trial 12 with value: 0.7816811185704035.
[I 2025-04-20 23:05:13,053] Trial 14 finished with value: 0.7805409568006022 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 0.1}. Best is trial 12 with value: 0.7816811185704035.
[I 2025-04-20 23:05:16,474] Trial 15 finished with value: 0.7839266067444086 and parameters: {'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7839266067444086.
[I 2025-04-20 23:05:19,893] Trial 16 finished with value: 0.7822254264045494 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7839266067444086.
[I 2025-04-20 23:05:23,297] Trial 17 finished with value: 0.7822254264045494 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7839266067444086.
[I 2025-04-20 23:05:26,712] Trial 18 finished with value: 0.7822254264045494 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7839266067444086.
[I 2025-04-20 23:05:30,144] Trial 19 finished with value: 0.7822254264045494 and parameters: {'depth': 6, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 15 with value: 0.7839266067444086.
[I 2025-04-20 23:05:40,019] A new study created in memory with name: catboost_optimization_0.9
[I 2025-04-20 23:05:43,165] Trial 0 finished with value: 0.577217769771046 and parameters: {'depth': 6, 'learning_rate': 0.001, 'l2_leaf_reg': 0.1}. Best is trial 0 with value: 0.577217769771046.
[I 2025-04-20 23:05:45,213] Trial 1 finished with value: 0.5791559553263633 and parameters: {'depth': 2, 'learning_rate': 0.01, 'l2_leaf_reg': 0.1}. Best is trial 1 with value: 0.5791559553263633.
[I 2025-04-20 23:05:52,825] Trial 2 finished with value: 0.586350509158958 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:00,710] Trial 3 finished with value: 0.5775301063332342 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 0.1}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:08,587] Trial 4 finished with value: 0.5784770825967016 and parameters: {'depth': 10, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:10,637] Trial 5 finished with value: 0.5832607002043578 and parameters: {'depth': 2, 'learning_rate': 0.1, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:17,691] Trial 6 finished with value: 0.576312682826401 and parameters: {'depth': 10, 'learning_rate': 0.001, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:23,829] Trial 7 finished with value: 0.5797337705177279 and parameters: {'depth': 8, 'learning_rate': 0.3, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:26,337] Trial 8 finished with value: 0.575494181196458 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:28,887] Trial 9 finished with value: 0.5748755998633995 and parameters: {'depth': 4, 'learning_rate': 0.001, 'l2_leaf_reg': 3.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:35,061] Trial 10 finished with value: 0.585272799267682 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:41,249] Trial 11 finished with value: 0.585272799267682 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:47,512] Trial 12 finished with value: 0.5829948097870877 and parameters: {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:50,757] Trial 13 finished with value: 0.5842527049359066 and parameters: {'depth': 6, 'learning_rate': 0.01, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:06:56,934] Trial 14 finished with value: 0.585272799267682 and parameters: {'depth': 8, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:07:04,609] Trial 15 finished with value: 0.586234727065495 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 1.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:07:12,602] Trial 16 finished with value: 0.5803004502838371 and parameters: {'depth': 10, 'learning_rate': 0.03, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:07:20,635] Trial 17 finished with value: 0.5793762447874825 and parameters: {'depth': 10, 'learning_rate': 0.1, 'l2_leaf_reg': 0.01}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:07:28,303] Trial 18 finished with value: 0.585760886273694 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 0.001}. Best is trial 2 with value: 0.586350509158958.
[I 2025-04-20 23:07:36,015] Trial 19 finished with value: 0.586350509158958 and parameters: {'depth': 10, 'learning_rate': 0.01, 'l2_leaf_reg': 6.0}. Best is trial 2 with value: 0.586350509158958.

In [19]:
res_jungle

,missing_rate,ROC-AUC,F1,Accuracy,Precision,Recall
0,0.2,0.9017±0.0036,0.6739±0.0095,0.7613±0.0063,0.7232±0.0114,0.6521±0.0087
1,0.5,0.7924±0.0056,0.5017±0.0082,0.6659±0.0069,0.6439±0.0229,0.5034±0.0060
2,0.9,0.5930±0.0067,0.3428±0.0051,0.5500±0.0075,0.3665±0.0064,0.3773±0.0042